services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod
    ports:
      - "8080:80"
